import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext({});

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    shopName: "Elite Shoe Shop",
    home: "Home",
    aboutUs: "About Us",
    shopNow: "Shop Now",
    customerReviews: "Customer Reviews",
    payHere: "Pay Here",
    contactUs: "Contact Us",
    login: "Login",
    logout: "Logout",
    myAccount: "My Account",
    cart: "Cart",
    search: "Search products...",
    featuredProducts: "Featured Products",
    specialOffers: "Special Offers",
    addToCart: "Add to Cart",
    viewCart: "View Cart",
    checkout: "Checkout",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    price: "Price",
    quantity: "Quantity",
    categories: "Categories",
    filterBy: "Filter By",
    brands: "Brands",
    priceRange: "Price Range",
    submitReview: "Submit Review",
    rating: "Rating",
    comment: "Comment",
    email: "Email",
    password: "Password",
    name: "Name",
    signUp: "Sign Up",
    signIn: "Sign In",
  },
  es: {
    shopName: "Tienda Elite de Zapatos",
    home: "Inicio",
    aboutUs: "Sobre Nosotros",
    shopNow: "Comprar Ahora",
    customerReviews: "Reseñas de Clientes",
    payHere: "Pagar Aquí",
    contactUs: "Contáctenos",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    myAccount: "Mi Cuenta",
    cart: "Carrito",
    search: "Buscar productos...",
    featuredProducts: "Productos Destacados",
    specialOffers: "Ofertas Especiales",
    addToCart: "Añadir al Carrito",
    viewCart: "Ver Carrito",
    checkout: "Pagar",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Descuento",
    price: "Precio",
    quantity: "Cantidad",
    categories: "Categorías",
    filterBy: "Filtrar Por",
    brands: "Marcas",
    priceRange: "Rango de Precios",
    submitReview: "Enviar Reseña",
    rating: "Calificación",
    comment: "Comentario",
    email: "Correo Electrónico",
    password: "Contraseña",
    name: "Nombre",
    signUp: "Registrarse",
    signIn: "Iniciar Sesión",
  },
  fr: {
    shopName: "Boutique de Chaussures Elite",
    home: "Accueil",
    aboutUs: "À Propos",
    shopNow: "Acheter Maintenant",
    customerReviews: "Avis Clients",
    payHere: "Payer Ici",
    contactUs: "Nous Contacter",
    login: "Connexion",
    logout: "Déconnexion",
    myAccount: "Mon Compte",
    cart: "Panier",
    search: "Rechercher des produits...",
    featuredProducts: "Produits Vedettes",
    specialOffers: "Offres Spéciales",
    addToCart: "Ajouter au Panier",
    viewCart: "Voir le Panier",
    checkout: "Commander",
    total: "Total",
    subtotal: "Sous-total",
    discount: "Réduction",
    price: "Prix",
    quantity: "Quantité",
    categories: "Catégories",
    filterBy: "Filtrer Par",
    brands: "Marques",
    priceRange: "Gamme de Prix",
    submitReview: "Soumettre un Avis",
    rating: "Évaluation",
    comment: "Commentaire",
    email: "Email",
    password: "Mot de Passe",
    name: "Nom",
    signUp: "S'inscrire",
    signIn: "Se Connecter",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
